--- 
abstract: Module to interface with the Lucene indexing webservice
author: 
  - Brian Cassidy <bricas@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-Lucene
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Data::Page: 0
  Encode: 0
  Exception::Class: 0
  Scalar::Util: 0
  URI: 0
  WWW::OpenSearch: 0.11
  XML::Atom: 0.25
  XML::LibXML: 0
  perl: 5.8.1
version: 0.05
