---
abstract: 'Module to interface with the Lucene indexing webservice'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Lucene
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Data::Page: 0
  Digest::SHA1: 0
  Encode: 0
  Exception::Class: 0
  Scalar::Util: 0
  URI: 0
  WWW::OpenSearch: 0.11
  XML::Atom: 0.25
  XML::LibXML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
